import Head from 'next/head'
import Card from '../components/Card'
export default function Home() {
  return (
    <>
      <Head>
        <title>TailwindCSS with Nesting</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main-wrapper">
        <Card />
      </main>
    </>
  )
}
